package main

func main() {
	//cipherText := "GCGFBJQKENGCPUMQGBNBLULGSPBETKDGGQMNMOCQESOLBEPMVTOAFZZFNDEGXAGBLGDBQ.GVLESHSVBBLCZMFSFRAHSVBKZENVTMLL.GFGVLVHGQMAVPBNDNNPVTGUFBDTMLRAXHPMOPEHQIGUBIGUMSPMOZVPVC.MCWVSNEPPMPVSNGBCLVLMZJKLU,OSRATFFGSOAGMSXHPMPMTVSOSPNAWVXSKMLZ!"
	cipherText1 := "GCGFBJQKENGCPUMQGBNBLULGSPBETKDGGQMNMOCQESOLBEPMVTOAFZZFNDEGXAGBLGDBQ"
	cipherText2 := "GVLESHSVBBLCZMFSFRAHSVBKZENVTMLL"
	cipherText3 := "GFGVLVHGQMAVPBNDNNPVTGUFBDTMLRAXHPMOPEHQIGUBIGUMSPMOZVPVC"
	cipherText4 := "MCWVSNEPPMPVSNGBCLVLMZJKLU"
	cipherText5 := "OSRATFFGSOAGMSXHPMPMTVSOSPNAWVXSKMLZ"

	//printCharFrequency(cipherText)
	//fmt.Printf(offsetCharsBy(cipherText, 25))
	startCryptogram([]string{cipherText1, cipherText2, cipherText3, cipherText4, cipherText5})
}
