package main

func main() {
	//cipherText := "GCGFBJQKENGCPUMQGBNBLULGSPBETKDGGQMNMOCQESOLBEPMVTOAFZZFNDEGXAGBLGDBQ.GVLESHSVBBLCZMFSFRAHSVBKZENVTMLL.GFGVLVHGQMAVPBNDNNPVTGUFBDTMLRAXHPMOPEHQIGUBIGUMSPMOZVPVC.MCWVSNEPPMPVSNGBCLVLMZJKLU,OSRATFFGSOAGMSXHPMPMTVSOSPNAWVXSKMLZ!"
	cipherText1 := "GCGFBJQKENGCPUMQGBNBLULGSPBETKDGGQMNMOCQESOLBEPMVTOAFZZFNDEGXAGBLGDBQ"
	//cipherText2 := "GVLESHSVBBLCZMFSFRAHSVBKZENVTMLL"
	//cipherText3 := "GFGVLVHGQMAVPBNDNNPVTGUFBDTMLRAXHPMOPEHQIGUBIGUMSPMOZVPVC"
	//cipherText4 := "MCWVSNEPPMPVSNGBCLVLMZJKLU"
	//cipherText5 := "OSRATFFGSOAGMSXHPMPMTVSOSPNAWVXSKMLZ"

	//printCharFrequency(cipherText)
	//fmt.Printf(offsetCharsBy(cipherText, 25))
	startCryptogram(cipherText1)
}
